### ISSUE TITLE
Something is wrong

### ISSUE THREAD

**Issue by jodiekurnia** [Widiskel/metaboss-bot#1]
Hi, I think something is wrong on your script, the event js didn't actually sending data to attack the boss.

**Comment by jodiekurnia** [comment]
Ett bahasa indo be dah.
Jadi begini bro, ora jalan ini script lu, apa yg salah ya? Json data yg di kirim di function sendattack() kah?

**Comment by Widiskel** [comment]
coba run ```git pull```, ada update baru bug fixing

jgn lupa abis itu ```npm update``` atau ```npm install```

**Comment by jodiekurnia** [comment]
sorry bro gw reply di sini, saran sih di event tambahin fitur claim treasure box bro, datanya lagi mau gw ambil nih, nunggu 1jam20menitan dlu -_-

**Comment by Widiskel** [comment]
> sorry bro gw reply di sini, saran sih di event tambahin fitur claim treasure box bro, datanya lagi mau gw ambil nih, nunggu 1jam20menitan dlu -_-

ok next gw tmbhin fitur itu, kmren g ditambahin soalny bgi gw sih lebih enk boxnya buka sendiri , jadi on bot bbrapa hari , dpt box bnyak bru dibuka sndiri 😅 berasa gachanya
