### ISSUE TITLE
It doesn't attack boss.

### ISSUE THREAD

**Issue by muggle69** [Widiskel/metaboss-bot#10]
Maybe the game update, now the script can not attack boss anymore, please check.

**Comment by Widiskel** [comment]
look at
https://github.com/Widiskel/metaboss-bot?tab=readme-ov-file#note

if the bot stuck it mean your credentials expired, but before that try restart the bot. sometimes metaboss websocket server is down, also dont forget to update the bot
![image](https://github.com/Widiskel/metaboss-bot/assets/97203329/76837384-9357-421f-a848-a380f6c80670)

**Comment by sythuan92** [comment]
Sr i have seem problem.
Do not actack boss. 
I dont know why.
![image](https://github.com/Widiskel/metaboss-bot/assets/38721519/430e425d-bb0c-40ee-b794-b8c6d5137158)

**Comment by Widiskel** [comment]
pull new update
