### ISSUE TITLE
tidak mendeteksi

### ISSUE THREAD

**Issue by isrealllairdrop** [Widiskel/metaboss-bot#2]
![Screenshot 2024-05-26 050750](https://github.com/Widiskel/metaboss-bot/assets/167641753/289324e1-be06-446c-a1e4-d11594b969c9)

sudah beberapa hari gini terus gan. mohon perbaikannya. terimakasih.

**Comment by Widiskel** [comment]
kalo user dan id udh undefined harus ambil informasi user lagi bg
https://github.com/Widiskel/metaboss-bot/raw/master/assets/gamesocket.png
