### ISSUE TITLE
Butuh bantuan

### ISSUE THREAD

**Issue by duclong2502** [Widiskel/metaboss-bot#3]
Halo. Saya sangat menyukai proyek Anda. Bisakah Anda menambahkan lebih banyak bagian penambangan? secara otomatis membuka permata hitam. Terima kasih banyak

**Comment by Widiskel** [comment]
hello, i want to add that feature soon. for now i don't have enough MTB coin so i can't do research and develop

**Comment by Widiskel** [comment]
added already, go pull new update

**Comment by duclong2502** [comment]
Wow amazing. Thank you very much!!!!

**Comment by Widiskel** [comment]
> Wow amazing. Thank you very much!!!!

sure, dont forget to ```git pull``` the new update
