### ISSUE TITLE
Error: WebSocket is not open: readyState 0 (CONNECTING)

### ISSUE THREAD

**Issue by AnhAnhii** [Widiskel/metaboss-bot#5]
After using the updated version, I always encounter this error after completing a round of the boss fight.
![image](https://github.com/Widiskel/metaboss-bot/assets/20750484/873e6b45-7f42-4c94-86e5-f4c0ddd9e3c1)

**Comment by Widiskel** [comment]
pull new update, or download from release

**Comment by Widiskel** [comment]
new update already handle that issue
