### ISSUE TITLE
{"code":1,"type":50,"data":{"type":4}}

### ISSUE THREAD

**Issue by AnhAnhii** [Widiskel/metaboss-bot#9]
-> Connecting to Websocket
-> Connected
{"code":1,"type":50,"data":{"type":4}}
-
Status : Missions id 4 (Join Telegram Channel) Completed

Is it possible to optionally skip the task? When I run it, it stops here and doesn't do anything further (I think it's because my account is not premium, so it can't complete the task and gets stuck here)
![image](https://github.com/Widiskel/metaboss-bot/assets/20750484/d767969d-52dd-415e-afae-96caa86ebe9f)

**Comment by muggle69** [comment]
> ## -> Connecting to Websocket
> -> Connected
> {"code":1,"type":50,"data":{"type":4}}
> Status : Missions id 4 (Join Telegram Channel) Completed
> 
> Is it possible to optionally skip the task? When I run it, it stops here and doesn't do anything further (I think it's because my account is not premium, so it can't complete the task and gets stuck here) ![image](https://private-user-images.githubusercontent.com/20750484/339847978-d767969d-52dd-415e-afae-96caa86ebe9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0NTU4ODMsIm5iZiI6MTcxODQ1NTU4MywicGF0aCI6Ii8yMDc1MDQ4NC8zMzk4NDc5NzgtZDc2Nzk2OWQtNTJkZC00MTVlLWFmYWUtOTZjYWE4NmViZTlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE1VDEyNDYyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyMTllN2U5ZTRlMmI3ZjU3MWY4NTI5NDY5MjhiYWVlOTA5NmI5MGE3Mjg1ZWNmNDJjZTExYjVlZmRkNjZiZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tEGJsSSAiqwomXXc3N6vk-RffhnJ5T0PPV9D3ES1obI)

Hello friend, how can you fix this?

**Comment by Widiskel** [comment]
it actually required missions, all my dummy account completed it so im not that got that error.

uncompletable missions is telegram missions and referal missions you can by pass it by see the ```index.js```
```js
const unCompleteMissions = event.missions.filter(
    (item) => !item.completed && item.id != 6
  );
```
      
add stucked id, like above, im add item.id != 6

6 is referral missions.

you can make it like this
```js
const unCompleteMissions = event.missions.filter(
  (item) => !item.completed && item.id != 6 && item.id != 4
);
```


after that the bot will skip the missions. close the issue after solved

**Comment by muggle69** [comment]
> it actually required missions, all my dummy account completed it so im not that got that error.
> 
> uncompletable missions is telegram missions and referal missions you can by pass it by see the `index.js`
> 
> ```js
> const unCompleteMissions = event.missions.filter(
>     (item) => !item.completed && item.id != 6
>   );
> ```
> 
> add stucked id, like above, im add item.id != 6
> 
> 6 is referral missions.
> 
> you can make it like this
> 
> ```js
> const unCompleteMissions = event.missions.filter(
>   (item) => !item.completed && item.id != 6 && item.id != 4
> );
> ```
> 
> after that the bot will skip the missions. close the issue after solved

Thank you so much, skip check mission id 4 the script run well. Please close the issue. All are OK now.
